language: node_js
node_js:
  - 12.19.0
cache: node
jobs:
  include:
    - stage: test
      script:
        - echo 'Deploy!!'
        - echo 'Installing Deps!'
        - node
        - echo 'Testing!'
        - node test:prod
    - stage: deploy
      script:
        - npm install -g firebase-tools
        - node build
        - firebase deploy --token "$FIREBASE_TOKEN"
stages:
  - name: test
    # require the type to be a PR
    if: type = pull_request
  - name: deploy
    # require the type to be push to master
    if: type = push AND branch = master